site_name: LeeCyberSec - Security Documentation
site_url: https://tusnj.github.io
site_description: Security Documentation with MkDocs.
site_author: Tusnj

# Header
nav:
  - 'Home': 'index.md'

  - 'Network Pentest':
    - 'Table of contents': 'network-pentest/index.md'
    
    - 'Network Scanning': 'network-pentest/scanning/index.md'

    - 'Common Services':
      - 'General Port Scan': 'network-pentest/common-services/00000-general.md'
      - 'Port 21 ftp': 'network-pentest/common-services/00021-ftp.md'
      - 'Port 22 ssh': 'network-pentest/common-services/00022-ssh.md'
      - 'Port 25 smtp': 'network-pentest/common-services/00025-smtp.md'
      - 'Port 53 dns': 'network-pentest/common-services/00053-dns.md'
      - 'Port 110 pop3': 'network-pentest/common-services/00110-pop3.md'
      - 'Port 111 nfs': 'network-pentest/common-services/00111-nfs.md'
      - 'Port 139,445 smb': 'network-pentest/common-services/00139-445-smb.md'
      - 'Port 161,199 snmp': 'network-pentest/common-services/00161-199-snmp.md'
      - 'Port 1443 mssql': 'network-pentest/common-services/01443-mssql.md'
      - 'Port 3306 mysql': 'network-pentest/common-services/03306-mysql.md'
      - 'Port 4505,4506 zmtp': 'network-pentest/common-services/04505-4506-zmtp.md'
      - 'Port 5432 postgresql': 'network-pentest/common-services/05432-postgresql.md'
      - 'Port 6379 redis ': 'network-pentest/common-services/06379-redis.md'
      - 'Port 27017 mongodb': 'network-pentest/common-services/27017-mongodb.md'

    - 'Remote Code Execution':
      - 'Unix RCE': 'network-pentest/remote-exploitation/Unix&Linux.md'
      - 'Windows RCE': 'network-pentest/remote-exploitation/windows.md'

    - 'File Transfer': 'network-pentest/file-transfer/index.md'
    - 'Password Attack': 'network-pentest/password-attack/index.md'
    - 'Redirec & Tunnel': 'network-pentest/port-redirection-tunneling/index.md'

    - 'Privilege Escalation':
      - 'Unix Privilege Escalation': 'network-pentest/privilege-escalation/Unix&Linux.md'
      - 'Windows Privilege Escalation': 'network-pentest/privilege-escalation/Windows.md'

  - 'Web Application':
    - 'Table of contents': 'web-application/index.md'

    - 'Web App Enumeration': 'web-application/enumeration.md'
    - 'Web App Exploitation': 'web-application/exploitation.md'

  # - 'Red Teaming':
  #   - 'Table of contents': 'red-teaming/index.md'
  #   - 'Info Gathering': 'network-pentest/reconnaissance/infor-gathering.md'

  #   - 'Unix Basics':
  #     - 'Commands': 'red-teaming/unix-system/commands.md'
  #     - 'Terminal': 'red-teaming/unix-system/terminal.md'
    
  - 'Active Directory':
    - 'Table of contents': 'active-directory/index.md'

    - 'AD Enumeration': 'active-directory/enumeration.md'
    - 'AD Authentication': 'active-directory/authentication.md'
    - 'AD Lateral Movement': 'active-directory/lateral-movement.md'
    - 'AD Persistent': 'active-directory/persistent.md'

  - 'Cloud Pentest':
    - 'Table of contents': 'cloud-pentest/index.md'

  # - 'Blog':
  #   - blog/index.md

    # - 'Exploit Development':
    #   - 'Buffer Overflow': 'red-teaming/exploit-dev/buffer-overflow/index.md'
    #   - 'Metasploit Framework': 'red-teaming/exploit-dev/metasploit-framework/index.md'
    #   - 'Nmap Scripting Engine': 'red-teaming/exploit-dev/nse-script/index.md'

    # - 'Malware development': 'red-teaming/malware-development/index.md'

    # - 'Moble Application': 'red-teaming/mobile-application/index.md'

    # - 'Wireless & RFID': 'red-teaming/wireless-rfid/index.md'

    # - 'Social Engineering': 'red-teaming/social-engineering/index.md'

    # - 'Powershell Empire': 'red-teaming/powershell-empire/index.md'

  # - 'DevSecOps':
  #   - 'Table of contents': 'devsecops/index.md'

  #   - 'Docker': 
  #     - 'Docker Basics': 'devsecops/docker/docker-basics.md'
  #     - 'Docker Hacking': 'devsecops/docker/docker-hacking.md'

  #   - 'CI/CD': 'devsecops/ci-cd/index.md'

  #   - 'SCA/OAST': 'devsecops/sca-oast/index.md'

  #   - 'SAST': 'devsecops/sast/index.md'

  #   - 'DAST': 'devsecops/dast/index.md'

  #   - 'Infrastructure': 'devsecops/iac/index.md'

  #   - 'Compliance': 'devsecops/cac/index.md'

  # - 'Blue Teaming':

  #   - 'Blue Team Training': 'blue-teaming/index.md'

  # - 'Walkthrough':

  #   - 'HackTheBox': 'walkthrough/hackthebox.md'
  #   - 'Proving Grounds': 'walkthrough/pg.md'
    #- 'TryHackMe': 'walkthrough/tryhackme.md'
    #- 'VulnHub': 'walkthrough/vulnhub.md'

#Theme and body
theme:
  name: material
  features:
    - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.sections
    # - navigation.expand
    - navigation.prune
    - navigation.indexes
    # - header.autohide
    - toc.integrate
    - navigation.top
  palette:
    primary: black
    scheme: slate
  logo: images/nika.jpg
  favicon: images/circle.png

markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - def_list
  - abbr
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - blog:
      authors: false
      # blog_toc: true
  - search

# Footer
extra:
  # generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/leecybersec
    - icon: fontawesome/brands/github
      link: https://github.com/Tusnj

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; 2020 - 2025 LeeCyberSec