site_name: LeeCyberSec

# Header
nav:
  - 'Home': 'index.md'
  
  - 'Red Teaming':

    - '__index__': 'red-teaming/index.md'

    - 'Unix System':

      - 'Filesystem': 'red-teaming/unix-system/filesystem.md'
      - 'Commands': 'red-teaming/unix-system/commands.md'
      - 'Services': 'red-teaming/unix-system/services.md'
      - 'Scripting': 'red-teaming/unix-system/scripting.md'
      - 'Terminal': 'red-teaming/unix-system/terminal.md'

    - 'Antivirus Evasion': 'red-teaming/antivirus-evasion/index.md'

    - 'Exploit Development':

      - 'Buffer Overflow': 'red-teaming/exploit-dev/buffer-overflow/index.md'

    - 'Malware development': 'red-teaming/malware-development/index.md'

  - 'Penetration Testing':

    - '__index__': 'penetration-testing/index.md'

    - 'External & Internal':

      - 'Reconnaissance':
        - 'Info Gathering': 'penetration-testing/external-internal/reconnaissance/infor-gathering.md'
        - 'Active Scanning': 'penetration-testing/external-internal/reconnaissance/active-scanning.md'    

      - 'Common Services':
        - 'general': 'penetration-testing/external-internal/common-services/general.md'
        - 'ftp 21': 'penetration-testing/external-internal/common-services/ftp-21.md'
        - 'smtp 25': 'penetration-testing/external-internal/common-services/smtp-25.md'
        - 'dns 53': 'penetration-testing/external-internal/common-services/dns-53.md'
        - 'pop3 110': 'penetration-testing/external-internal/common-services/pop3-110.md'
        - 'nfs 111': 'penetration-testing/external-internal/common-services/nfs-111.md'
        - 'smb 139,445': 'penetration-testing/external-internal/common-services/smb-139-445.md'
        - 'snmp 161': 'penetration-testing/external-internal/common-services/snmp-161.md'
        - 'mssql 1443': 'penetration-testing/external-internal/common-services/mssql-1443.md'
        - 'mysql 3306': 'penetration-testing/external-internal/common-services/mysql-3306.md'
        - 'postgresql 5432': 'penetration-testing/external-internal/common-services/postgresql-5432.md'

      - 'Remote Exploitation':

        - 'Unix': 'penetration-testing/external-internal/remote-exploitation/linux.md'
        - 'Windows': 'penetration-testing/external-internal/remote-exploitation/windows.md'

      - 'File Transfer': 'penetration-testing/external-internal/file-transfer/index.md'

      - 'Privilege Escalation':

        - 'Unix': 'penetration-testing/external-internal/privilege-escalation/unix.md'
        - 'Windows': 'penetration-testing/external-internal/privilege-escalation/windows.md'

      - 'Post Exploitation': 'penetration-testing/external-internal/post-exploitation/index.md'

    - 'Web Application':

      - 'Enumeration': 'penetration-testing/web-application/enumeration.md'

      - 'Exploitation': 'penetration-testing/web-application/exploitation.md'

    - 'Moble Application': 'penetration-testing/mobile-application/index.md'

    - 'Wireless & RFID': 'penetration-testing/wireless-rfid/index.md'

    - 'Social Engineering': 'penetration-testing/social-engineering/index.md'

  - 'Walkthrough':

    - '__index__': 'walkthrough/index.md'

    - 'Hack The Box':

      - 'Lame': 'walkthrough/hackthebox/Lame/index.md'
      - 'Legacy': 'walkthrough/hackthebox/Legacy/index.md'
      - 'Devel': 'walkthrough/hackthebox/Devel/index.md'
      - 'Popcorn': 'walkthrough/hackthebox/Popcorn/index.md'
      - 'Beep': 'walkthrough/hackthebox/Beep/index.md'
      - 'Optimum': 'walkthrough/hackthebox/Optimum/index.md'
      - 'Bastard': 'walkthrough/hackthebox/Bastard/index.md'
      - 'Cronos': 'walkthrough/hackthebox/Cronos/index.md'
      - 'Blue': 'walkthrough/hackthebox/Blue/index.md'
      - 'Nineveh': 'walkthrough/hackthebox/Nineveh/index.md'
      - 'Shocker': 'walkthrough/hackthebox/Shocker/index.md'

    - 'VulnHub':

      - 'Brainpan 1': 'walkthrough/vulnhub/Brainpan-1/index.md'
      - 'Pentester Lab: S2-052': 'walkthrough/vulnhub/S2-052/index.md'
      - 'DC: 9': 'walkthrough/vulnhub/DC-9/index.md'
      - 'symfonos: 1': 'walkthrough/vulnhub/symfonos-1/index.md'
      - 'mod_jk double-decoding': 'walkthrough/vulnhub/mod_jk-double-decoding/index.md'
      - 'SolidState: 1': 'walkthrough/vulnhub/SolidState-1/index.md'
      - 'Wintermute: 1 (Straylight)': 'walkthrough/vulnhub/Wintermute-1-Straylight/index.md'
      - 'Wintermute: 1 (Neuromancer)': 'walkthrough/vulnhub/Wintermute-1-Neuromancer/index.md'

  - 'Blue Teaming':

    - '__index__': 'blue-teaming/index.md'

    - 'Blue Team Training': 'https://www.blueteamsacademy.com'
  
  - 'About Me': 'about/index.md'

#Theme and body
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    primary: 'black'
    scheme: slate

markdown_extensions:
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.snippets
  - attr_list

# Footer
extra:
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/leecybersec
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/leecybersec
    - icon: fontawesome/brands/github
      link: https://github.com/leecybersec
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/leecybersec
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UC_2YYw_h37UiMUaPv_tB5Rw

copyright: Copyright &copy; 2020 - 2021 LeeCyberSec