site_name: LeeCyberSec

# Header
nav:
    - 'Home': 'index.md'
    - 'Penetration Testing':
      - 'Network Pentest':
        - 'Auto Scan':
          - 'nmapAutomator': 'penetration-testing/network/auto-scan/nmapAutomator.md'
          - 'AutoRecon': 'penetration-testing/network/auto-scan/AutoRecon.md'
        - 'nmap':
          - 'all ports': 'penetration-testing/network/nmap/all-ports.md'
          - 'Script Scan': 'penetration-testing/network/nmap/script-scan.md'
        - 'Common Services':
          - 'General': 'penetration-testing/network/common-services/general.md'

      - 'Wireless Pentest': 'penetration-testing/wireless.md'

      - 'Web Application': 'penetration-testing/web-application.md'

      - 'Moble Application': 'penetration-testing/moble-application.md'

      - 'Thick Clients': 'penetration-testing/thick-clients.md'

    - 'CVE Exploit': 'cve-exploit/comming-soon.md'
    - 'Work Through':
      - 'Introduction': 'work-through/introduction.md'
      - 'Hack The Box': 'work-through/hackthebox/comming-soon.md'
      - 'VulnHub': 'work-through/vulnhub/comming-soon.md'
    - 'Blue Teaming':
      - 'About Blue Team': 'blue-teaming/comming-soon.md'
    - 'Splunk Certifacate':
      - 'About Splunk': 'splunk/comming-soon.md'
    - 'About Me': 'about.md'

#Theme and body
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
  palette:
    primary: 'black'
    scheme: slate
markdown_extensions:
  - attr_list
  - pymdownx.tabbed

# Footer
extra:
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/leecybersec
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/leecybersec
    - icon: fontawesome/brands/github
      link: https://github.com/leecybersec
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/leecybersec
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UC_2YYw_h37UiMUaPv_tB5Rw
copyright: Copyright &copy; 2020 - 2021 LeeCyberSec