site_name: LeeCyberSec

# Header
nav:
    - 'Home': 'index.md'
    - 'Penetration Testing':
      - 'About Pentest': 'penetration-testing/index.md'
      - 'Network Pentest':
        - 'Auto Scan':
          - 'nmapAutomator': 'penetration-testing/network/auto-scan/nmapAutomator.md'
          - 'AutoRecon': 'penetration-testing/network/auto-scan/AutoRecon.md'
        - 'nmap':
          - 'all ports': 'penetration-testing/network/nmap/all-ports.md'
          - 'Script Scan': 'penetration-testing/network/nmap/script-scan.md'
        - 'Common Services':
          - 'General': 'penetration-testing/network/common-services/general.md'
          - 'ftp 21': 'penetration-testing/network/common-services/ftp-21.md'
          - 'smtp 25': 'penetration-testing/network/common-services/smtp-25.md'
          - 'smb 139,445': 'penetration-testing/network/common-services/smb-139-445.md'
        - 'Remote Code Execution':
          - 'Linux': 'penetration-testing/network/remote-code-execution/linux.md'
          - 'Windows': 'penetration-testing/network/remote-code-execution/windows.md'
        - 'File Transfer': 'penetration-testing/network/file-transfer/index.md'
        - 'Privilege Escalation':
          - 'Windows Privilege Escalation': 'penetration-testing/privilege-escalation/windows-privilege-escalation.md'
          - 'Linux Privilege Escalation': 'penetration-testing/privilege-escalation/linux-privilege-escalation.md'
        - 'Buffer Overflow': 'penetration-testing/network/buffer-overflow/index.md'

      - 'Wireless Pentest': 'penetration-testing/wireless.md'

      - 'Web Application':
        - 'Enumeration': 'penetration-testing/web-application/enumeration.md'
        - 'Exploitation': 'penetration-testing/web-application/exploitation.md'
        - 'Execute Commands': 'penetration-testing/web-application/execute-commands.md'
        - 'Databases':
          - 'Mysql': 'penetration-testing/web-application/databases/mysql.md'
          - 'SQLite': 'penetration-testing/web-application/databases/SQLite.md'
          - 'MSSQL': 'penetration-testing/web-application/databases/MSSQL.md'
          - 'PostgreSQL': 'penetration-testing/web-application/databases/PostgreSQL.md'

      - 'Moble Application': 'penetration-testing/mobile-application.md'

      - 'Thick Clients': 'penetration-testing/thick-clients.md'

    - 'Walk Through':
      - 'Machines for OSCP':
        - 'Machines List': 'walk-through/machines-for-oscp/machines-list.md'
        - 'Hack The Box':
          - 'Compromised': 
            - 'Walk Through': 'walk-through/machines-for-oscp/hackthebox/Compromised/index.md'
            - 'nmapAutomator': 'walk-through/machines-for-oscp/hackthebox/Compromised/nmapAutomator.md'

        - 'VulnHub':
          - 'Brainpan':
            - 'Walk Through': 'walk-through/machines-for-oscp/vulnhub/Brainpan/index.md'
            - 'nmapAutomator': 'walk-through/machines-for-oscp/vulnhub/Brainpan/nmapAutomator.md'
          - 'Pentester Lab: S2-052':
            - 'Walk Through': 'walk-through/machines-for-oscp/vulnhub/S2-052/index.md'
            - 'nmapAutomator': 'walk-through/machines-for-oscp/vulnhub/S2-052/nmapAutomator.md'

      - 'CVE Exploit':
        - 'CVE-2017-9805': '/walk-through/machines-for-oscp/vulnhub/S2-052/#cve-2017-9805'

    - 'Hack Tricks':
      - 'Commands Linux': 'hacktricks/commands-linux.md'

    - 'Blue Teaming':
      - 'About Blue Team': 'blue-teaming/index.md'
      - 'Blue Team Training': 'blue-teaming/training.md'
      - 'About Splunk': 'blue-teaming/splunk.md'
    - 'About Me': 'about.md'

#Theme and body
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    primary: 'black'
    scheme: slate
markdown_extensions:
  - attr_list
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.superfences

# Footer
extra:
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/leecybersec
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/leecybersec
    - icon: fontawesome/brands/github
      link: https://github.com/leecybersec
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/leecybersec
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UC_2YYw_h37UiMUaPv_tB5Rw
copyright: Copyright &copy; 2020 - 2021 LeeCyberSec