site_name: LeeCyberSec

# Header
nav:
  - 'Home': 'index.md'
  
  - 'Red Teaming':
    - 'Table of contents': 'red-teaming/index.md'

    - 'Unix Basics':
      - 'Commands': 'red-teaming/unix-system/commands.md'
      - 'Terminal': 'red-teaming/unix-system/terminal.md'

    - 'External & Internal':
      - 'Reconnaissance':
        - 'Info Gathering': 'red-teaming/network-pentest/reconnaissance/infor-gathering.md'
        - 'Active Scanning': 'red-teaming/network-pentest/reconnaissance/active-scanning.md'    

      - 'Common Services':
        - 'general': 'red-teaming/network-pentest/common-services/00000-general.md'
        - '21 ftp': 'red-teaming/network-pentest/common-services/00021-ftp.md'
        - '22 ssh': 'red-teaming/network-pentest/common-services/00022-ssh.md'
        - '25 smtp': 'red-teaming/network-pentest/common-services/00025-smtp.md'
        - '53 dns': 'red-teaming/network-pentest/common-services/00053-dns.md'
        - '110 pop3': 'red-teaming/network-pentest/common-services/00110-pop3.md'
        - '111 nfs': 'red-teaming/network-pentest/common-services/00111-nfs.md'
        - '139,445 smb': 'red-teaming/network-pentest/common-services/00139-445-smb.md'
        - '161,199 snmp': 'red-teaming/network-pentest/common-services/00161-199-snmp.md'
        - '1443 mssql': 'red-teaming/network-pentest/common-services/01443-mssql.md'
        - '3306 mysql': 'red-teaming/network-pentest/common-services/03306-mysql.md'
        - '4505,4506 zmtp': 'red-teaming/network-pentest/common-services/04505-4506-zmtp.md'
        - '5432 postgresql': 'red-teaming/network-pentest/common-services/05432-postgresql.md'
        - '6379 redis ': 'red-teaming/network-pentest/common-services/06379-redis.md'
        - '27017 mongodb': 'red-teaming/network-pentest/common-services/27017-mongodb.md'

      - 'Remote Exploitation':
        - 'Unix&Linux': 'red-teaming/network-pentest/remote-exploitation/Unix&Linux.md'
        - 'Windows': 'red-teaming/network-pentest/remote-exploitation/windows.md'

      - 'File Transfer': 'red-teaming/network-pentest/file-transfer/index.md'
      - 'Password Attack': 'red-teaming/network-pentest/password-attack/index.md'
      - 'Redirec & Tunnel': 'red-teaming/network-pentest/port-redirection-tunneling/index.md'

      - 'Privilege Escalation':
        - 'Unix&Linux': 'red-teaming/network-pentest/privilege-escalation/Unix&Linux.md'
        - 'Windows': 'red-teaming/network-pentest/privilege-escalation/Windows.md'
    
    - 'Active Directory':
      - 'Enumeration': 'red-teaming/active-directory/enumeration.md'
      - 'Authentication': 'red-teaming/active-directory/authentication.md'
      - 'Lateral Movement': 'red-teaming/active-directory/lateral-movement.md'
      - 'Persistent': 'red-teaming/active-directory/persistent.md'

    - 'Web Application':
      - 'Enumeration': 'red-teaming/web-application/enumeration.md'

      - 'Exploitation': 'red-teaming/web-application/exploitation.md'

    - 'Exploit Development':
      - 'Buffer Overflow': 'red-teaming/exploit-dev/buffer-overflow/index.md'
      - 'Metasploit Framework': 'red-teaming/exploit-dev/metasploit-framework/index.md'
      - 'Nmap Scripting Engine': 'red-teaming/exploit-dev/nse-script/index.md'

    - 'Malware development': 'red-teaming/malware-development/index.md'

    # - 'Moble Application': 'red-teaming/mobile-application/index.md'

    # - 'Wireless & RFID': 'red-teaming/wireless-rfid/index.md'

    - 'Social Engineering': 'red-teaming/social-engineering/index.md'

    # - 'Powershell Empire': 'red-teaming/powershell-empire/index.md'

  - 'DevSecOps':
    - 'Table of contents': 'devsecops/index.md'

    - 'Docker': 
      - 'Docker Basics': 'devsecops/docker/docker-basics.md'
      - 'Docker Hacking': 'devsecops/docker/docker-hacking.md'

    - 'CI/CD': 'devsecops/ci-cd/index.md'

    - 'SCA/OAST': 'devsecops/sca-oast/index.md'

    - 'SAST': 'devsecops/sast/index.md'

    - 'DAST': 'devsecops/dast/index.md'

    - 'Infrastructure': 'devsecops/iac/index.md'

    - 'Compliance': 'devsecops/cac/index.md'

  - 'Blue Teaming':

    - 'Blue Team Training': 'blue-teaming/index.md'

  - 'Walkthrough':

    - 'HackTheBox': 'walkthrough/hackthebox.md'
    - 'Proving Grounds': 'walkthrough/pg.md'
    #- 'TryHackMe': 'walkthrough/tryhackme.md'
    #- 'VulnHub': 'walkthrough/vulnhub.md'

#Theme and body
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    primary: 'black'
    scheme: slate

markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - def_list
  - abbr
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

# Footer
extra:
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/leecybersec
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/leecybersec
    - icon: fontawesome/brands/github
      link: https://github.com/leecybersec
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/leecybersec
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UC_2YYw_h37UiMUaPv_tB5Rw

copyright: Copyright &copy; 2020 - 2022 LeeCyberSec