site_name: LeeCyberSec

# Header
nav:
  - 'Home': 'index.md'
  
  - 'Red Teaming':

    - 'Unix System':
      - 'Filesystem': 'red-teaming/unix-system/filesystem.md'
      - 'Commands': 'red-teaming/unix-system/commands.md'
      - 'Services': 'red-teaming/unix-system/services.md'
      - 'Scripting': 'red-teaming/unix-system/scripting.md'
      - 'Terminal': 'red-teaming/unix-system/terminal.md'

    - 'Antivirus Evasion': 'red-teaming/antivirus-evasion/index.md'

    - 'Exploit Development':
      - 'Buffer Overflow': 'red-teaming/exploit-dev/buffer-overflow/index.md'
      - 'Metasploit Framework': 'red-teaming/exploit-dev/metasploit-framework/index.md'
      - 'Nmap Scripting Engine': 'red-teaming/exploit-dev/nse-script/index.md'

    - 'Malware development': 'red-teaming/malware-development/index.md'

    - 'Powershell Empire': 'red-teaming/powershell-empire/index.md'    

  - 'Penetration Testing':

    - 'External & Internal':
      - 'Reconnaissance':
        - 'Info Gathering': 'penetration-testing/external-internal/reconnaissance/infor-gathering.md'
        - 'Active Scanning': 'penetration-testing/external-internal/reconnaissance/active-scanning.md'    

      - 'Common Services':
        - 'general': 'penetration-testing/external-internal/common-services/00000-general.md'
        - '21 ftp': 'penetration-testing/external-internal/common-services/00021-ftp.md'
        - '25 smtp': 'penetration-testing/external-internal/common-services/00025-smtp.md'
        - '53 dns': 'penetration-testing/external-internal/common-services/00053-dns.md'
        - '110 pop3': 'penetration-testing/external-internal/common-services/00110-pop3.md'
        - '111 nfs': 'penetration-testing/external-internal/common-services/00111-nfs.md'
        - '139,445 smb': 'penetration-testing/external-internal/common-services/00139-445-smb.md'
        - '161,199 snmp': 'penetration-testing/external-internal/common-services/00161-199-snmp.md'
        - '1443 mssql': 'penetration-testing/external-internal/common-services/01443-mssql.md'
        - '3306 mysql': 'penetration-testing/external-internal/common-services/03306-mysql.md'
        - '4505,4506 zmtp': 'penetration-testing/external-internal/common-services/04505-4506-zmtp.md'
        - '5432 postgresql': 'penetration-testing/external-internal/common-services/05432-postgresql.md'
        - '6379 redis ': 'penetration-testing/external-internal/common-services/06379-redis.md'
        - '27017 mongodb': 'penetration-testing/external-internal/common-services/27017-mongodb.md'

      - 'Remote Exploitation':
        - 'Unix&Linux': 'penetration-testing/external-internal/remote-exploitation/Unix&Linux.md'
        - 'Windows': 'penetration-testing/external-internal/remote-exploitation/windows.md'

      - 'File Transfer': 'penetration-testing/external-internal/file-transfer/index.md'
      - 'Password Attack': 'penetration-testing/external-internal/password-attack/index.md'
      - 'Redirec & Tunnel': 'penetration-testing/external-internal/port-redirection-tunneling/index.md'

      - 'Privilege Escalation':
        - 'Unix Enumeration': 'penetration-testing/external-internal/privilege-escalation/local-enum/Unix&Linux.md'
        - 'Unix Escalation': 'penetration-testing/external-internal/privilege-escalation/common-escal/Unix&Linux.md'
        - 'Windows Enumeration': 'penetration-testing/external-internal/privilege-escalation/local-enum/Windows.md'
        - 'Windows Escalation': 'penetration-testing/external-internal/privilege-escalation/common-escal/Windows.md'
    
    - 'Active Directory':
      - 'Enumeration': 'penetration-testing/active-directory/enumeration.md'
      - 'Authentication': 'penetration-testing/active-directory/authentication.md'
      - 'Lateral Movement': 'penetration-testing/active-directory/lateral-movement.md'
      - 'Persistent': 'penetration-testing/active-directory/persistent.md'

    - 'Web Application':
      - 'Enumeration': 'penetration-testing/web-application/enumeration.md'

      - 'Exploitation': 'penetration-testing/web-application/exploitation.md'

    - 'Moble Application': 'penetration-testing/mobile-application/index.md'

    - 'Wireless & RFID': 'penetration-testing/wireless-rfid/index.md'

    - 'Social Engineering': 'penetration-testing/social-engineering/index.md'

  - 'Walkthrough':

    - 'HackTheBox': 'walkthrough/hackthebox.md'
    - 'Proving Grounds': 'walkthrough/pg.md'
    - 'TryHackMe': 'walkthrough/tryhackme.md'
    - 'VulnHub': 'walkthrough/vulnhub.md'
    
  - 'Blue Teaming':

    - 'Blue Team Training': 'blue-teaming/index.md'
  
  - 'About Me': 'about/index.md'

#Theme and body
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    primary: 'black'
    scheme: slate

markdown_extensions:
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.snippets
  - attr_list
  - pymdownx.tasklist
 

# Footer
extra:
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/leecybersec
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/leecybersec
    - icon: fontawesome/brands/github
      link: https://github.com/leecybersec
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/leecybersec
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UC_2YYw_h37UiMUaPv_tB5Rw

copyright: Copyright &copy; 2020 - 2021 LeeCyberSec