site_name: LeeCyberSec

# Header
nav:
    - 'Home': 'index.md'
    - 'Penetration Testing':
      - 'About Pentest': 'penetration-testing/index.md'
      - 'Network Pentest':
        - 'Reconnaissance':
          - 'recon script': 'penetration-testing/network/reconnaissance/recon-script.md'
          - 'infor gathering': 'penetration-testing/network/reconnaissance/infor-gathering.md'
          - 'scanning': 'penetration-testing/network/reconnaissance/scanning.md'          
        - 'Common Services':
          - 'general': 'penetration-testing/network/common-services/general.md'
          - 'ftp 21': 'penetration-testing/network/common-services/ftp-21.md'
          - 'smtp 25': 'penetration-testing/network/common-services/smtp-25.md'
          - 'dns 53': 'penetration-testing/network/common-services/dns-53.md'
          - 'pop3 110': 'penetration-testing/network/common-services/pop3-110.md'
          - 'nfs 111': 'penetration-testing/network/common-services/nfs-111.md'
          - 'smb 139,445': 'penetration-testing/network/common-services/smb-139-445.md'
          - 'snmp 161': 'penetration-testing/network/common-services/snmp-161.md'
          - 'mssql 1443': 'penetration-testing/network/common-services/mssql-1443.md'
        - 'Remote Code Execution':
          - 'Linux': 'penetration-testing/network/remote-code-execution/linux.md'
          - 'Windows': 'penetration-testing/network/remote-code-execution/windows.md'
        - 'File Transfer': 'penetration-testing/network/file-transfer/index.md'
        - 'Privilege Escalation':
          - 'Windows Privilege Escalation': 'penetration-testing/privilege-escalation/windows-privilege-escalation.md'
          - 'Linux Privilege Escalation': 'penetration-testing/privilege-escalation/linux-privilege-escalation.md'
        - 'Buffer Overflow': 'penetration-testing/network/buffer-overflow/index.md'

      - 'Wireless Pentest': 'penetration-testing/wireless/index.md'

      - 'Web Application':
        - 'Enumeration': 'penetration-testing/web-application/enumeration.md'
        - 'Exploitation': 'penetration-testing/web-application/exploitation.md'
        - 'Databases':
          - 'Mysql': 'penetration-testing/web-application/databases/mysql.md'
          - 'SQLite': 'penetration-testing/web-application/databases/SQLite.md'
          - 'MSSQL': 'penetration-testing/web-application/databases/MSSQL.md'
          - 'PostgreSQL': 'penetration-testing/web-application/databases/PostgreSQL.md'

      - 'Moble Application': 'penetration-testing/mobile-application/index.md'

      - 'Hacking Thick Clients': 'penetration-testing/thick-clients/index.md'

      - 'Social Engineering': 'penetration-testing/social-engineering/index.md'

    - 'Walk Through':
      - 'Machines for OSCP':
        - 'Machines List': 'walk-through/machines-for-oscp/machines-list.md'
        - 'Hack The Box':
          - 'Lame': 
            - 'Walk Through': 'walk-through/machines-for-oscp/hackthebox/Lame/index.md'
            - 'nmapAutomator': 'walk-through/machines-for-oscp/hackthebox/Lame/nmapAutomator.md'            
            - 'LinEnum': 'walk-through/machines-for-oscp/hackthebox/Lame/LinEnum.md'
          - 'Legacy': 
            - 'Walk Through': 'walk-through/machines-for-oscp/hackthebox/Legacy/index.md'
            - 'nmapAutomator': 'walk-through/machines-for-oscp/hackthebox/Legacy/nmapAutomator.md'
          - 'Compromised': 
            - 'Walk Through': 'walk-through/machines-for-oscp/hackthebox/Compromised/index.md'
            - 'nmapAutomator': 'walk-through/machines-for-oscp/hackthebox/Compromised/nmapAutomator.md'

        - 'VulnHub':
          - 'Brainpan':
            - 'Walk Through': 'walk-through/machines-for-oscp/vulnhub/Brainpan/index.md'
            - 'nmapAutomator': 'walk-through/machines-for-oscp/vulnhub/Brainpan/nmapAutomator.md'
          - 'Pentester Lab: S2-052':
            - 'Walk Through': 'walk-through/machines-for-oscp/vulnhub/S2-052/index.md'
            - 'nmapAutomator': 'walk-through/machines-for-oscp/vulnhub/S2-052/nmapAutomator.md'
          - 'DC: 9':
            - 'Walk Through': 'walk-through/machines-for-oscp/vulnhub/DC-9/index.md'
            - 'nmapAutomator': 'walk-through/machines-for-oscp/vulnhub/DC-9/nmapAutomator.md'
          - 'symfonos: 1':
            - 'Walk Through': 'walk-through/machines-for-oscp/vulnhub/symfonos-1/index.md'
            - 'nmapAutomator': 'walk-through/machines-for-oscp/vulnhub/symfonos-1/nmapAutomator.md'
          - 'mod_jk double-decoding':
            - 'Walk Through': 'walk-through/machines-for-oscp/vulnhub/mod_jk-double-decoding/index.md'
            - 'nmapAutomator': 'walk-through/machines-for-oscp/vulnhub/mod_jk-double-decoding/nmapAutomator.md'

      - 'CVE Exploit':
        - 'CVE-2017-9805': '/walk-through/machines-for-oscp/vulnhub/S2-052/#cve-2017-9805'
        - 'CVE-2017-0144 (Eternalblue/MS17-010)': '/walk-through/machines-for-oscp/hackthebox/Legacy/#cve-2017-0144-eternalbluems17-010'
        - 'CVE-2008-4250 (MS08-067)': '/walk-through/machines-for-oscp/hackthebox/Legacy/#cve-2008-4250-ms08-067'
        - 'CVE-2007-2447': '/walk-through/machines-for-oscp/hackthebox/Lame/#cve-2007-2447'
        - 'CVE-2004-2687': '/walk-through/machines-for-oscp/hackthebox/Lame/#cve-2004-2687'

    - 'Hack Tricks':
      - 'Unix Commands':
        - 'Basic Commands': 'hacktricks/unix_system/commands/basic-commands.md'
        - 'Commands to Shell': 'hacktricks/unix_system/commands/commands-to-shell.md'
      - 'Unix Filesystem': 'hacktricks/unix_system/filesystem.md'
      - 'Basic Services': 'hacktricks/unix_system/basic_services.md'
      - 'Bash Scripting': 'hacktricks/unix_system/bash_scripting.md'
      - 'Custom Terminal': 'hacktricks/unix_system/terminal.md'

    - 'Blue Teaming':
      - 'About Blue Team': 'blue-teaming/index.md'
      - 'Blue Team Training': 'https://www.blueteamsacademy.com'
      - 'Splunk Research': 'blue-teaming/splunk-research.md'
    - 'About Me': 'about.md'

#Theme and body
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    primary: 'black'
    scheme: slate
markdown_extensions:
  - attr_list
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.superfences

# Footer
extra:
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/leecybersec
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/leecybersec
    - icon: fontawesome/brands/github
      link: https://github.com/leecybersec
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/leecybersec
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UC_2YYw_h37UiMUaPv_tB5Rw
copyright: Copyright &copy; 2020 - 2021 LeeCyberSec