site_name: LeeCyberSec

# Header
nav:
  - 'Home': 'index.md'
  
  - 'Red Teaming':

    - 'Unix System':
      - 'Filesystem': 'red-teaming/unix-system/filesystem.md'
      - 'Commands': 'red-teaming/unix-system/commands.md'
      - 'Services': 'red-teaming/unix-system/services.md'
      - 'Scripting': 'red-teaming/unix-system/scripting.md'
      - 'Terminal': 'red-teaming/unix-system/terminal.md'

    - 'Antivirus Evasion': 'red-teaming/antivirus-evasion/index.md'

    - 'Exploit Development':
      - 'Buffer Overflow': 'red-teaming/exploit-dev/buffer-overflow/index.md'
      - 'Metasploit Framework': 'red-teaming/exploit-dev/metasploit-framework/index.md'
      - 'Nmap Scripting Engine': 'red-teaming/exploit-dev/nse-script/index.md'

    - 'Malware development': 'red-teaming/malware-development/index.md'

    - 'Powershell Empire': 'red-teaming/powershell-empire/index.md'    

  - 'Penetration Testing':

    - 'External & Internal':
      - 'Reconnaissance':
        - 'Info Gathering': 'penetration-testing/external-internal/reconnaissance/infor-gathering.md'
        - 'Active Scanning': 'penetration-testing/external-internal/reconnaissance/active-scanning.md'    

      - 'Common Services':
        - 'general': 'penetration-testing/external-internal/common-services/general.md'
        - 'ftp 21': 'penetration-testing/external-internal/common-services/ftp-21.md'
        - 'smtp 25': 'penetration-testing/external-internal/common-services/smtp-25.md'
        - 'dns 53': 'penetration-testing/external-internal/common-services/dns-53.md'
        - 'pop3 110': 'penetration-testing/external-internal/common-services/pop3-110.md'
        - 'nfs 111': 'penetration-testing/external-internal/common-services/nfs-111.md'
        - 'smb 139,445': 'penetration-testing/external-internal/common-services/smb-139-445.md'
        - 'snmp 161': 'penetration-testing/external-internal/common-services/snmp-161.md'
        - 'mssql 1443': 'penetration-testing/external-internal/common-services/mssql-1443.md'
        - 'mysql 3306': 'penetration-testing/external-internal/common-services/mysql-3306.md'
        - 'postgresql 5432': 'penetration-testing/external-internal/common-services/postgresql-5432.md'
        - 'mongodb 27017': 'penetration-testing/external-internal/common-services/mongodb-27017.md'

      - 'Remote Exploitation':
        - 'Unix&Linux': 'penetration-testing/external-internal/remote-exploitation/Unix&Linux.md'
        - 'Windows': 'penetration-testing/external-internal/remote-exploitation/windows.md'

      - 'File Transfer': 'penetration-testing/external-internal/file-transfer/index.md'
      - 'Password Attack': 'penetration-testing/external-internal/password-attack/index.md'
      - 'Redirec & Tunnel': 'penetration-testing/external-internal/port-redirection-tunneling/index.md'

      - 'Privilege Escalation':
        - 'Unix Enumeration': 'penetration-testing/external-internal/privilege-escalation/local-enum/Unix&Linux.md'
        - 'Unix Escalation': 'penetration-testing/external-internal/privilege-escalation/common-escal/Unix&Linux.md'
        - 'Windows Enumeration': 'penetration-testing/external-internal/privilege-escalation/local-enum/Windows.md'
        - 'Windows Escalation': 'penetration-testing/external-internal/privilege-escalation/common-escal/Windows.md'
    
    - 'Active Directory':
      - 'Enumeration': 'penetration-testing/active-directory/enumeration.md'
      - 'Authentication': 'penetration-testing/active-directory/authentication.md'
      - 'Lateral Movement': 'penetration-testing/active-directory/lateral-movement.md'
      - 'Persistent': 'penetration-testing/active-directory/persistent.md'

    - 'Web Application':
      - 'Enumeration': 'penetration-testing/web-application/enumeration.md'

      - 'Exploitation': 'penetration-testing/web-application/exploitation.md'

    - 'Moble Application': 'penetration-testing/mobile-application/index.md'

    - 'Wireless & RFID': 'penetration-testing/wireless-rfid/index.md'

    - 'Social Engineering': 'penetration-testing/social-engineering/index.md'

  - 'Walkthrough':

    - 'HackTheBox': 'walkthrough/hackthebox.md'
    - 'Proving Grounds': 'walkthrough/pg.md'
    - 'TryHackMe': 'walkthrough/tryhackme.md'
    - 'VulnHub': 'walkthrough/vulnhub.md'
    
  - 'Blue Teaming':

    - 'Blue Team Training': 'blue-teaming/index.md'
  
  - 'About Me': 'about/index.md'

#Theme and body
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    primary: 'black'
    scheme: slate

markdown_extensions:
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.snippets
  - attr_list
  - pymdownx.tasklist
 

# Footer
extra:
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/leecybersec
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/leecybersec
    - icon: fontawesome/brands/github
      link: https://github.com/leecybersec
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/leecybersec
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UC_2YYw_h37UiMUaPv_tB5Rw

copyright: Copyright &copy; 2020 - 2021 LeeCyberSec