site_name: LeeCyberSec

# Header
nav:
  - 'Home': 'index.md'
  
  - 'Red Teaming':
    - '__index__': 'red-teaming/index.md'

    - 'Unix System':
      - 'Filesystem': 'red-teaming/unix-system/filesystem.md'
      - 'Commands': 'red-teaming/unix-system/commands.md'
      - 'Services': 'red-teaming/unix-system/services.md'
      - 'Scripting': 'red-teaming/unix-system/scripting.md'
      - 'Terminal': 'red-teaming/unix-system/terminal.md'

    - 'Antivirus Evasion': 'red-teaming/antivirus-evasion/index.md'

    - 'Exploit Development':
      - 'Buffer Overflow': 'red-teaming/exploit-dev/buffer-overflow/index.md'

    - 'Malware development': 'red-teaming/malware-development/index.md'

  - 'Penetration Testing':

    - '__index__': 'penetration-testing/index.md'

    - 'External & Internal':
      - 'Reconnaissance':
        - 'Info Gathering': 'penetration-testing/external-internal/reconnaissance/infor-gathering.md'
        - 'Active Scanning': 'penetration-testing/external-internal/reconnaissance/active-scanning.md'    

      - 'Common Services':
        - 'general': 'penetration-testing/external-internal/common-services/general.md'
        - 'ftp 21': 'penetration-testing/external-internal/common-services/ftp-21.md'
        - 'smtp 25': 'penetration-testing/external-internal/common-services/smtp-25.md'
        - 'dns 53': 'penetration-testing/external-internal/common-services/dns-53.md'
        - 'pop3 110': 'penetration-testing/external-internal/common-services/pop3-110.md'
        - 'nfs 111': 'penetration-testing/external-internal/common-services/nfs-111.md'
        - 'smb 139,445': 'penetration-testing/external-internal/common-services/smb-139-445.md'
        - 'snmp 161': 'penetration-testing/external-internal/common-services/snmp-161.md'
        - 'mssql 1443': 'penetration-testing/external-internal/common-services/mssql-1443.md'
        - 'mysql 3306': 'penetration-testing/external-internal/common-services/mysql-3306.md'
        - 'postgresql 5432': 'penetration-testing/external-internal/common-services/postgresql-5432.md'
        - 'mongodb 27017': 'penetration-testing/external-internal/common-services/mongodb-27017.md'

      - 'Remote Exploitation':
        - 'Unix&Linux': 'penetration-testing/external-internal/remote-exploitation/Unix&Linux.md'
        - 'Windows': 'penetration-testing/external-internal/remote-exploitation/Windows.md'

      - 'File Transfer': 'penetration-testing/external-internal/file-transfer/index.md'
      - 'Password Attack': 'penetration-testing/external-internal/password-attack/index.md'
      - 'Redirec & Tunnel': 'penetration-testing/external-internal/port-redirection-tunneling/index.md'

      - 'Privilege Escalation':
        - 'Local Enumeration':
          - 'Unix&Linux': 'penetration-testing/external-internal/privilege-escalation/local-enum/Unix&Linux.md'
          - 'Windows': 'penetration-testing/external-internal/privilege-escalation/local-enum/Windows.md'

        - 'Common Escalation':
          - 'Unix&Linux': 'penetration-testing/external-internal/privilege-escalation/common-escal/Unix&Linux.md'
          - 'Windows': 'penetration-testing/external-internal/privilege-escalation/common-escal/Windows.md'

    - 'Web Application':
      - 'Enumeration': 'penetration-testing/web-application/enumeration.md'

      - 'Exploitation': 'penetration-testing/web-application/exploitation.md'

    - 'Moble Application': 'penetration-testing/mobile-application/index.md'

    - 'Wireless & RFID': 'penetration-testing/wireless-rfid/index.md'

    - 'Social Engineering': 'penetration-testing/social-engineering/index.md'

  - 'Walkthrough':

    - '__index__': 'walkthrough/index.md'

    - 'Hack The Box':
      - 'HTB Lame': 'walkthrough/hackthebox/Lame/index.md'
      - 'HTB Legacy': 'walkthrough/hackthebox/Legacy/index.md'
      - 'HTB Devel': 'walkthrough/hackthebox/Devel/index.md'
      - 'HTB Popcorn': 'walkthrough/hackthebox/Popcorn/index.md'
      - 'HTB Beep': 'walkthrough/hackthebox/Beep/index.md'
      - 'HTB Optimum': 'walkthrough/hackthebox/Optimum/index.md'
      - 'HTB Bastard': 'walkthrough/hackthebox/Bastard/index.md'
      - 'HTB Cronos': 'walkthrough/hackthebox/Cronos/index.md'
      - 'HTB Blue': 'walkthrough/hackthebox/Blue/index.md'
      - 'HTB Nineveh': 'walkthrough/hackthebox/Nineveh/index.md'
      - 'HTB Shocker': 'walkthrough/hackthebox/Shocker/index.md'
      - 'HTB Bashed': 'walkthrough/hackthebox/Bashed/index.md'
      - 'HTB Nibbles': 'walkthrough/hackthebox/Nibbles/index.md'
      - 'HTB Jerry': 'walkthrough/hackthebox/Jerry/index.md'
      - 'HTB Bastion': 'walkthrough/hackthebox/Bastion/index.md'
      - 'HTB Tabby': 'walkthrough/hackthebox/Tabby/index.md'
      - 'HTB ServMon': 'walkthrough/hackthebox/ServMon/index.md'
      - 'HTB Canape': 'walkthrough/hackthebox/Canape/index.md'
      - 'HTB Help': 'walkthrough/hackthebox/Help/index.md'

    - 'TryHackMe':
      - 'Mr Robot': 'walkthrough/tryhackme/MrRobot/index.md'
      - 'Thompson': 'walkthrough/tryhackme/Thompson/index.md'
      - 'Kenobi': 'walkthrough/tryhackme/Kenobi/index.md'
      - 'Ignite': 'walkthrough/tryhackme/Ignite/index.md'
      - 'Steel Mountain': 'walkthrough/tryhackme/SteelMountain/index.md'
      - 'HackPark': 'walkthrough/tryhackme/HackPark/index.md'
      
    - 'VulnHub':
      - 'Brainpan 1': 'walkthrough/vulnhub/Brainpan-1/index.md'
      - 'Pentester Lab: S2-052': 'walkthrough/vulnhub/S2-052/index.md'
      - 'SolidState: 1': 'walkthrough/vulnhub/SolidState-1/index.md'
      - 'Wintermute: 1 (Straylight)': 'walkthrough/vulnhub/Wintermute-1-Straylight/index.md'
      - 'Wintermute: 1 (Neuromancer)': 'walkthrough/vulnhub/Wintermute-1-Neuromancer/index.md'

  - 'Blue Teaming':
    - '__index__': 'blue-teaming/index.md'

    - 'Blue Team Training': 'https://www.blueteamsacademy.com'
  
  - 'About Me': 'about/index.md'

#Theme and body
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    primary: 'black'
    scheme: slate

markdown_extensions:
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.snippets
  - attr_list

# Footer
extra:
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/leecybersec
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/leecybersec
    - icon: fontawesome/brands/github
      link: https://github.com/leecybersec
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/leecybersec
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UC_2YYw_h37UiMUaPv_tB5Rw

copyright: Copyright &copy; 2020 - 2021 LeeCyberSec